In [14]:
import numpy as np 

In [15]:
%timeit [j**4 for j in range (1,9)]

2.56 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
%timeit np.arange(1,9)**4

2.82 µs ± 329 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [21]:

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [22]:

arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [23]:
arr = np.array(42) # zero dim arr

print(arr)


42


In [42]:
# one -dim array
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.ndim)# print dimesnion of array 

[1 2 3 4 5]
1


In [25]:
# two dim array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [27]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [28]:
# An array can have any number of dimensions.
# When the array is created, 
# you can define the number of dimensions by using the ndmin argument.



arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [29]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [30]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [32]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


Slicing arrays
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].
If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1

In [182]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [183]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [184]:
# slicing 2d array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) # first entry row no , 2 entry from start to end 

[7 8 9]


In [185]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) # first entry row from 1 to 2. 2 entry index 2  
# From both elements, return index 2:

[3 8]


In [190]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [2, 4, 1, 2, 5]]) 
#if dim is not same then dont work

print(arr[0:2, 2]) #run only for 1 and 2 row 

[3 8]


In [192]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [2, 4, 1, 2, 5]]) 
#if dim is not same then dont work

print(arr[0:3, 2])

[3 8 1]


In [39]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Data type in numpy

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [66]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [67]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [68]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [69]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [73]:
#Converting Data Type on Existing Arrays

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

#or 

arr2 = np.array([1.1, 2.1, 3.1], np.int8)
print(arr2.dtype)



[1 2 3]
int32
int8


In [82]:
arr= np.array([1,2,4,5])

new1= arr.astype('f')
new2= arr.astype('i8') #2-16/4-32/8-64

new3= np.int_(new1)

print("data type:" , arr.dtype)
print("data type:" , new1.dtype)
print("data type:" , new2.dtype)
print("data type:" , new3.dtype)

print(arr)
print(new1)
print(new2)

data type: int32
data type: float32
data type: int64
data type: int32
[1 2 4 5]
[1. 2. 4. 5.]
[1 2 4 5]


In [83]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# Shape of an Array

In [86]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


print(arr)
print()
print(arr.shape) # type of matrix 

[[1 2 3 4]
 [5 6 7 8]]

(2, 4)


In [89]:
arr1 = np.array([1, 2, 3, 4], ndmin=5)

print(arr1)
print('shape of array :', arr1.shape) # no of row in [-],[-][-][-][-----]
print(arr1.ndim)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
5


In [98]:
#reshape

arr4= np.array([1,2,3,4,5,6,7,8])
print(arr4)
print(arr4.ndim)

print()

x= arr4.reshape(4,2) # (row,col)

print(x)

print(x.ndim)


[1 2 3 4 5 6 7 8]
1

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2


In [101]:
#reshape 3D

arr4= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr4)
print(arr4.ndim)

print()
# The outermost dimension 
# will have 2 arrays that contains 3 arrays, each with 2 elements:
x= arr4.reshape(2,3,2) # (row,col)

print(x)

print(x.ndim)
# Flattening the arrays
# Flattening array means converting a multidimensional array into a 1D array.
one = x.reshape(-1)
print(one, one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12] 1


In [102]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# arithmetic operator 

In [103]:
var= np.array([1,2,3,4])

varadd= var+3
print(varadd)

[4 5 6 7]


In [104]:
var1= np.array([1,2,3,4])
var2= np.array([1,2,3,4])



varadd= var1+var2 
print(varadd)

[2 4 6 8]


In [105]:
var= np.array([1,2,3,4])
new= var-3
print(new)

[-2 -1  0  1]


In [106]:
var= np.array([1,2,3,4])
new= var*3
print(new)

[ 3  6  9 12]


In [107]:
var= np.array([1,2,3,4])
new= var//3
print(new)

[0 0 1 1]


In [108]:
var= np.array([1,2,3,4])
new= var/3
print(new)

[0.33333333 0.66666667 1.         1.33333333]


In [109]:
var1= np.array([1,2,3,4])
var2= np.array([1,2,3,4])

new= var1-var2 
print(new)

[0 0 0 0]


In [110]:
var1= np.array([1,2,3,4])
var2= np.array([1,2,3,4])

varadd= np.add(var1,var2) 
print(varadd)

[2 4 6 8]


In [111]:
var1= np.array([1,2,3,4])
var2= np.array([1,2,3,4])

varadd= np.add(var1,3) 
print(varadd)

[4 5 6 7]


In [112]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [113]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [116]:
#2d array

var21= np.array([[1,2,3,4],[2,3,4,5]])
var22= np.array([[2,4,5,7],[7,6,3,4]])
print(var21)
print()
print(var22)
print()

varnew= var21+ var22

print(varnew)

[[1 2 3 4]
 [2 3 4 5]]

[[2 4 5 7]
 [7 6 3 4]]

[[ 3  6  8 11]
 [ 9  9  7  9]]


In [117]:
var21= np.array([[1,2,3,4],[2,3,4,5]])
var22= np.array([[2,4,5,7],[7,6,3,4]])
print(var21)
print()
print(var22)
print()

varnew= np.subtract(var21, var22)

print(varnew)

[[1 2 3 4]
 [2 3 4 5]]

[[2 4 5 7]
 [7 6 3 4]]

[[-1 -2 -2 -3]
 [-5 -3  1  1]]


In [118]:
var21= np.array([[1,2,3,4],[2,3,4,5]])
var22= np.array([[2,4,5,7],[7,6,3,4]])
print(var21)
print()
print(var22)
print()

varnew= np.multiply(var21, var22) # not matrrix mutiplication

print(varnew)

[[1 2 3 4]
 [2 3 4 5]]

[[2 4 5 7]
 [7 6 3 4]]

[[ 2  8 15 28]
 [14 18 12 20]]


In [128]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [129]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [130]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [119]:
var21= np.array([[1,2,3,4],[2,3,4,5]])
var22= np.array([[2,4,5,7],[7,6,3,4]])
print(var21)
print()
print(var22)
print()

varnew= np.divide(var21, var22)

print(varnew)

[[1 2 3 4]
 [2 3 4 5]]

[[2 4 5 7]
 [7 6 3 4]]

[[0.5        0.5        0.6        0.57142857]
 [0.28571429 0.5        1.33333333 1.25      ]]


In [120]:
var21= np.array([[1,2,3,4],[2,3,4,5]])
var22= np.array([[2,4,5,7],[7,6,3,4]])
print(var21)
print()
print(var22)
print()

varnew= np.mod(var21, var22)

print(varnew)

[[1 2 3 4]
 [2 3 4 5]]

[[2 4 5 7]
 [7 6 3 4]]

[[1 2 3 4]
 [2 3 1 1]]


In [121]:
var21= np.array([[1,2,3,4],[2,3,4,5]])
var22= np.array([[2,4,5,7],[7,6,3,4]])
print(var21)
print()
print(var22)
print()

varnew= np.power(var21,2)

print(varnew)

[[1 2 3 4]
 [2 3 4 5]]

[[2 4 5 7]
 [7 6 3 4]]

[[ 1  4  9 16]
 [ 4  9 16 25]]


In [122]:
var21= np.array([[1,2,3,4],[2,3,4,5]])
var22= np.array([[2,4,5,7],[7,6,3,4]])
print(var21)
print()
print(var22)
print()

varnew= np.power(var21, var22)

print(varnew)

[[1 2 3 4]
 [2 3 4 5]]

[[2 4 5 7]
 [7 6 3 4]]

[[    1    16   243 16384]
 [  128   729    64   625]]


In [123]:
var21= np.array([[1,2,3,4],[2,3,4,5]])
var22= np.array([[2,4,5,7],[7,6,3,4]])
print(var21)
print()
print(var22)
print()

varnew= np.reciprocal(var21, var22)

print(varnew)

[[1 2 3 4]
 [2 3 4 5]]

[[2 4 5 7]
 [7 6 3 4]]

[[1 0 0 0]
 [0 0 0 0]]


In [124]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [126]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [127]:
# partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


In [131]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [138]:
var= np.array([1,2,3,4,5,7])

print("min:",np.min(var))
print("min:",np.min(var), np.argmin(var))
print()
print("max:",np.max(var))
print("max:",np.max(var),np.argmax(var))


min: 1
min: 1 0

max: 7
max: 7 5


In [148]:
var21= np.array([[6,9,1,4],[2,6,4,5]])

print(np.min(var21,axis=0),'index',np.argmin(var21))
print(np.min(var21,axis=1),"index",np.argmin(var21))
print("sqrt:", np.sqrt(var21))

[2 6 1 4] index 2
[1 2] index 2
sqrt: [[2.44948974 3.         1.         2.        ]
 [1.41421356 2.44948974 2.         2.23606798]]


In [145]:
var21= np.array([[6,9,1,4],[2,6,4,5]])

print(np.max(var21,axis=0))
print(np.max(var21,axis=1))

[6 9 4 5]
[9 6]


In [150]:
var2= np.array([6,7,1])
print(np.sin(var2))
print(np.cos(var2))

[-0.2794155   0.6569866   0.84147098]
[0.96017029 0.75390225 0.54030231]


#boardcasting array 
meansd dim of array size isnot same 

In [154]:
var1= np.array([3,4,3,2,1])
var2= np.array([5,7,3,2,7])

print(np.add(var1,var2))

[ 8 11  6  4  8]


In [155]:
var1= np.array([3,4,3,2,1])
var2= np.array([5,7,3,7])

print(np.add(var1,var2))

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [174]:
var1= np.array([3,4,3,2,1]) # here we do mistake but code is run 
print("dim of 1*5", var1.shape)
print()
print(var1)

var2= np.array([[5],[7],[3],[7]])
print("dim 4*1",var2.shape)
print()
print(var2)

print("(1,4)* (5*1): result (4,5)")
print(np.add(var1,var2))
print()

dim of 1*5 (5,)

[3 4 3 2 1]
dim 4*1 (4, 1)

[[5]
 [7]
 [3]
 [7]]
(1,4)* (5*1): result (4,5)
[[ 8  9  8  7  6]
 [10 11 10  9  8]
 [ 6  7  6  5  4]
 [10 11 10  9  8]]



In [178]:
var1= np.array([[3,4,3,2,1]]) 
print("dim of 1*5", var1.shape)
print()
print(var1)
print()


var2= np.array([[5],[7],[3],[7]])
print("dim 4*1",var2.shape)
print()
print(var2)


print()
print("(1,4)* (5*1): result (4,5)")
print(np.add(var1,var2))
print()

dim of 1*5 (1, 5)

[[3 4 3 2 1]]

dim 4*1 (4, 1)

[[5]
 [7]
 [3]
 [7]]

(1,4)* (5*1): result (4,5)
[[ 8  9  8  7  6]
 [10 11 10  9  8]
 [ 6  7  6  5  4]
 [10 11 10  9  8]]



In [197]:
x=([2,8,9,2,3,4])
for i in x:
    print(i)

2
8
9
2
3
4


In [198]:
x=np.array([2,8,9,2,3,4])
for i in x:
    print(i)

2
8
9
2
3
4


In [200]:
y= np.array([[2,3,4],[2,4,5]])

for j in y:
    print(j)
    
for j in y:
    for i in j:
        print(i)

[2 3 4]
[2 4 5]
2
3
4
2
4
5


In [201]:
# avoid for loop again and again
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [202]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']): # data in string
  print(x)

b'1'
b'2'
b'3'


In [203]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [204]:
# value with index in array 

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [205]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
# arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8],[2,3,5,0]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

# Copy vs View

The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [214]:
var = np.array([2,3,5])

co= var.copy()

print("var", var)
print("copy",co)

var [2 3 5]
copy [2 3 5]


In [216]:
var = np.array([1, 2, 3, 4, 5])
co = var.copy()
var[0] = 42  #change in original not in copy
co[1]=3 # change in copy 
print(var)
print(co)

[42  2  3  4  5]
[1 3 3 4 5]


In [217]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [218]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)

[31  2  3  4  5]


# Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

In [219]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [220]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [221]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [222]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [223]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [224]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [225]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [229]:
arr = np.array([1, 2, 3, 4, 5, 6,7])

newarr = np.array_split(arr, 3) # 3 is no of array

print(newarr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [231]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)
print(newarr[0])

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]


In [232]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [233]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [234]:
#Split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#Split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

In [235]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays


You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [236]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4) #find index of 4 

print(x)

(array([3, 5, 6], dtype=int64),)


In [237]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays

In [238]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [239]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [241]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6]) # kis variable ko kaha uplaod kar sakte hai 

print(x)

[1 2 3]


Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [242]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [243]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [244]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [245]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [246]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [247]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [248]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [249]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [250]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [251]:
#shuffle function

arr= np.array([1,2,3,4,5])

np.random.shuffle(arr)
print(arr) #leave the arrangment

[2 5 3 1 4]


In [252]:
arr= np.array([1,2,3,4,5])

np.random.shuffle(arr)
print(arr)

[3 4 1 5 2]


In [253]:
#unique 

arr=np.array([1,2,4,2,4,3,2,2,2])

x= np.unique(arr)
print(x)

[1 2 3 4]


In [254]:
arr=np.array([1,2,4,2,4,3,2,2,2])

x= np.unique(arr,return_index= True )
print(x)

(array([1, 2, 3, 4]), array([0, 1, 5, 2], dtype=int64))


In [266]:
arr=np.array([1,2,4,2,4,3,2,2,2])

x= np.unique(arr,return_index= True , return_counts= True)
print(x)

(array([1, 2, 3, 4]), array([0, 1, 5, 2], dtype=int64), array([1, 5, 1, 2], dtype=int64))


In [276]:
arr1 = np.array([2,3,5,2,7,8,9,6,7])
resize= np.resize(arr1,(2,3))
print(resize)  

[[2 3 5]
 [2 7 8]]


flatten order reduce 
order {C, F,a, k

In [270]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr)
print(arr.flatten())


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [274]:
arr = np.array([1,3,4,5,7,8,9])
resize= np.resize(arr,(3,2))
print(resize)
print(resize.flatten())

[[1 3]
 [4 5]
 [7 8]]
[1 3 4 5 7 8]


In [279]:
arr = np.array([1,3,4,5,7,8,9])
resize= np.resize(arr,(3,2))
print(resize)
print("Flatten",resize.flatten(order= 'F'))
print("ravel",np.ravel(resize,order= 'F'))
print("Flatten",resize.flatten(order= 'A'))
print("ravel",np.ravel(resize,order= 'A'))
print("Flatten",resize.flatten(order= 'C'))
print("ravel",np.ravel(resize,order= 'C'))

[[1 3]
 [4 5]
 [7 8]]
Flatten [1 4 7 3 5 8]
ravel [1 4 7 3 5 8]
Flatten [1 3 4 5 7 8]
ravel [1 3 4 5 7 8]
Flatten [1 3 4 5 7 8]
ravel [1 3 4 5 7 8]


# insert dunction

In [288]:
arr= np.array([1,2,3,4])

print(arr)
print(arr.dtype)

v= np.insert(arr,1,5) #(name,postion, value)
print(v)

v1= np.insert(arr,(1,3),9) #(name,postion, value)
print(v1)

v2= np.insert(arr,(1,3),9.5) #(name,postion, value)
print(v2)

[1 2 3 4]
int32
[1 5 2 3 4]
[1 9 2 3 9 4]
[1 9 2 3 9 4]


In [290]:
a= np.array([[1,2,3],[2,3,5]])

v5= np.insert(a,1,6,axis=0) #(name,postion, value)
print(v5)

[[1 2 3]
 [6 6 6]
 [2 3 5]]


In [291]:
a= np.array([[1,2,3],[2,3,5]])

v5= np.insert(a,1,6,axis=1) #(name,postion, value)
print(v5)

[[1 6 2 3]
 [2 6 3 5]]


In [293]:
a= np.array([[1,2,3],[2,3,5]])

v5= np.insert(a,1,[22,6,7],axis=0) #(name,postion, value)
print(v5)

[[ 1  2  3]
 [22  6  7]
 [ 2  3  5]]


In [295]:
a= np.array([1,2,3,2,3,5])

v5= np.append(a,6.5) 
print(v5)

[1.  2.  3.  2.  3.  5.  6.5]


In [296]:
a= np.array([[1,2,3],[2,3,5]])

v5= np.append(a,[23,3,6]) 
print(v5)

[ 1  2  3  2  3  5 23  3  6]


In [298]:
a= np.array([1,2,3,2,3,5])
 
print(a)
d= np.delete(a,3)
print(d)

[1 2 3 2 3 5]
[1 2 3 3 5]


In [302]:
# matrix in numpy array

arr= np.matrix([[1,2,3],[2,4,5]])
print(arr)
print(type(arr))




[[1 2 3]
 [2 4 5]]
<class 'numpy.matrix'>


In [304]:
arr= np.array([[1,2,3],[2,4,5]])
print(arr)
print(type(arr))

[[1 2 3]
 [2 4 5]]
<class 'numpy.ndarray'>


In [305]:
arr1= np.matrix([[1,2,3],[2,4,5]])
arr2= np.matrix([[1,2,3],[2,4,5]])

print(arr1+arr2)

[[ 2  4  6]
 [ 4  8 10]]


In [306]:
arr1= np.matrix([[1,2,3],[2,4,5]])
arr2= np.matrix([[1,2,3],[2,4,5]])

print(arr1*arr2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [308]:
arr1= np.matrix([[1,2,3],[2,4,5],[2,3,4]])
arr2= np.matrix([[1,2,3],[2,4,5],[3,4,5]])

print(arr1*arr2)

[[14 22 28]
 [25 40 51]
 [20 32 41]]


In [309]:
arr1= np.array([[1,2,3],[2,4,5],[2,3,4]])
arr2= np.array([[1,2,3],[2,4,5],[3,4,5]])

print(arr1*arr2)

[[ 1  4  9]
 [ 4 16 25]
 [ 6 12 20]]


matrix function 
Transpose
swapaxes
inverse 
power
determinate 

In [319]:
arr1= np.array([[1,2,3],[2,4,5],[7,8,9]])
arr2= np.array([[1,2,3],[2,4,5],[3,4,5]])
print(arr1)
print()
# print(arr2)
print()
v= np.transpose(arr1)
print(v)


#othere way
print()
print(arr1.T)
print()
print(arr1)
print()
print(np.swapaxes(arr1,0,1))

[[1 2 3]
 [2 4 5]
 [7 8 9]]


[[1 2 7]
 [2 4 8]
 [3 5 9]]

[[1 2 7]
 [2 4 8]
 [3 5 9]]

[[1 2 3]
 [2 4 5]
 [7 8 9]]

[[1 2 7]
 [2 4 8]
 [3 5 9]]


In [320]:
arr1= np.array([[1,2],[7,5]])
print(arr1)
print()
v= np.linalg.inv(arr1)
print(v)

[[1 2]
 [7 5]]

[[-0.55555556  0.22222222]
 [ 0.77777778 -0.11111111]]


In [324]:
arr1= np.matrix([[1,2],[3,2]])
print(arr1)
print()
v= np.linalg.matrix_power(arr1,2)
print(v)
print()

v= np.linalg.matrix_power(arr1,-2)
print(v)
print()

v= np.linalg.matrix_power(arr1,0)
print(v)
print()

[[1 2]
 [3 2]]

[[ 7  6]
 [ 9 10]]

[[ 0.625  -0.375 ]
 [-0.5625  0.4375]]

[[1 0]
 [0 1]]



In [330]:
arr1= np.array([[1,2,3],[8,4,5],[7,8,9]])
arr2= np.array([[1,9,3],[3,4,5],[3,8,5]])
print(arr1)
print()
v1= np.linalg.det(arr1)
print(v1)
print()


print(arr2)
print()

v2= np.linalg.det(arr2)
print(v2)


[[1 2 3]
 [8 4 5]
 [7 8 9]]

30.000000000000004

[[1 9 3]
 [3 4 5]
 [3 8 5]]

16.000000000000007


# youtube 

In [41]:
l=[]
for i in range(1,5):
        int_1= int(input('enter:'))
        l.append(int_1)
print(np.array(l))

enter:12
enter:3
enter:3
enter:3
[12  3  3  3]


In [44]:
#zero dim array
ar_zero= np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [45]:
ar_zero= np.zeros(4)

ar_zero1= np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]
[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [46]:
ar_one= np.ones(4)
ar_ones1= np.ones((3,4))

print(ar_one)
print()
print(ar_ones1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
ar_one= np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [50]:
ar = np.empty(4) # note here empty arrray store previous entry and give it
print(ar)

[1. 1. 1. 1.]


In [51]:
ar_range = np.arange(4)
print(ar_range)

[0 1 2 3]


In [52]:
# diagonal 
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
# diagonal 
ar_dia = np.eye(4,7)
print(ar_dia)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [54]:
#linspace 
ar_lin= np.linspace(0,20, num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# random

In [56]:
#rand():    the function is used to generate a random betwwen 0 t 1 
#randn()    close to zero , postive negative both vale 
#anf(): [0.0,1.0)
#randint(): range between to values 


var= np.random.rand(4) # four dim array all values lies in betwwen 0 to 1
print(var)

[0.95159197 0.22069219 0.9092944  0.36239803]


In [58]:
var1= np.random.rand(3,5) # four dim array all values lies in betwwen 0 to 1
print(var1)

[[0.73552332 0.01171542 0.37812616 0.69009241 0.72831374]
 [0.69073124 0.98704231 0.36344509 0.24127136 0.81849736]
 [0.78733578 0.27655996 0.4052727  0.0512619  0.94316704]]


In [59]:
var2= np.random.randn(5) # four dim array all values close to zero
print(var2)

[-2.46999142  0.69062517 -0.72299297  0.05884429 -2.8362963 ]


In [61]:
var3= np.random.ranf(5) # 0 include but not 1 
print(var3)

[0.62359826 0.93433785 0.23385217 0.29060928 0.07336625]


In [63]:
var4= np.random.randint(2,7) 
print(var4)

6


In [65]:
var4= np.random.randint(2,27,7) # (min, max ,total no gen) 
print(var4)

[16 20  7 22  8 10 11]
